In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [ ]:
tab_arr = []

model_dict = {
    "deitsmall": "facebook/deit-small-patch16-224",
    "dinobase": "facebook/dinov2-base",
    "vitlarge": "google/vit-large-patch16-224"
}

dataset_dict = {
    "mnist": "mnist",
    "cifar100": "cifar100",
    "imagenet1k": "imagenet-1k"
}

for dataset in ["mnist", "cifar100", "imagenet1k"]:
    for model in ["deitsmall"]:#, "deitbase"]:
        tab = pd.read_csv(f"../outputs/{model}_{dataset}.csv")
        for i in range(0, 12):
            tab[f"layer_{i}_keep"] = tab[f"layer_{i}_keep"].apply(lambda x: [int(n) for n in x.split(" ")])
        tab["total_heads_kept"] = tab[[f"layer_{i}_keep" for i in range(0, 12)]].apply(lambda x: sum([len(l) for l in x]), axis=1)
        tab["head_dict"] = tab.apply(lambda row: {int(f"{i}"): row[f"layer_{i}_keep"] for i in range(0, 12) if len(row[f"layer_{i}_keep"]) < 6}, axis=1)
        tab["dataset"] = dataset_dict[dataset]
        tab["model"] = model_dict[model]
        tab_arr.append(tab)


experiments = pd.concat(tab_arr, ignore_index=True)
experiments["skip"] = []
experiments["mlp_skip"] = []
experiments["attn_skip"] = []
experiments["skip_translator"] = "identity"
experiments["mlp_mode"] = "identity"
experiments["attn_mode"] = "identity"
experiments_data = experiments[["dataset", "model", "total_heads_kept", "head_dict", "threshold"]]

experiments["head_dict"] = experiments["head_dict"].apply(str)
experiments = experiments[["dataset", "model", "skip", "mlp_skip", "attn_skip", "head_dict", "skip_translator", "mlp_mode", "attn_mode"]]
experiments = experiments.drop_duplicates()
experiments.to_csv("../outputs/experiments.csv", index=False)

In [18]:
experiments

,threshold,layer_0_keep,layer_1_keep,layer_2_keep,layer_3_keep,layer_4_keep,layer_5_keep,layer_6_keep,layer_7_keep,layer_8_keep,layer_9_keep,layer_10_keep,layer_11_keep,total_heads_kept,head_dict,dataset,model
0,0.05,[0],[0],[0],"[0, 4]",[0],[0],[0],[0],"[0, 1]",[0],[0],[0],14,"{0: [0], 1: [0], 2: [0], 3: [0, 4], 4: [0], 5:...",mnist,deitsmall
1,0.10,[0],[0],[0],"[0, 4]",[0],[0],[0],[0],"[0, 1]",[0],[0],[0],14,"{0: [0], 1: [0], 2: [0], 3: [0, 4], 4: [0], 5:...",mnist,deitsmall
2,0.15,[0],[0],[0],"[0, 4]",[0],[0],[0],[0],"[0, 1]",[0],[0],[0],14,"{0: [0], 1: [0], 2: [0], 3: [0, 4], 4: [0], 5:...",mnist,deitsmall
3,0.20,[0],[0],[0],"[0, 4]",[0],[0],[0],[0],"[0, 1]",[0],[0],[0],14,"{0: [0], 1: [0], 2: [0], 3: [0, 4], 4: [0], 5:...",mnist,deitsmall
4,0.25,[0],"[0, 3]",[0],"[0, 4]",[0],[0],[0],[0],"[0, 1]",[0],[0],[0],15,"{0: [0], 1: [0, 3], 2: [0], 3: [0, 4], 4: [0],...",mnist,deitsmall
5,0.30,[0],"[0, 3]",[0],"[0, 4]",[0],[0],[0],[0],"[0, 1]",[0],[0],[0],15,"{0: [0], 1: [0, 3], 2: [0], 3: [0, 4], 4: [0],...",mnist,deitsmall
6,0.35,[0],"[0, 3]",[0],"[0, 4]","[0, 2]","[0, 2]",[0],[0],"[0, 1]",[0],[0],[0],17,"{0: [0], 1: [0, 3], 2: [0], 3: [0, 4], 4: [0, ...",mnist,deitsmall
7,0.40,[0],"[0, 3]","[0, 4]","[0, 4]","[0, 2]","[0, 2]",[0],[0],"[0, 1]",[0],[0],[0],18,"{0: [0], 1: [0, 3], 2: [0, 4], 3: [0, 4], 4: [...",mnist,deitsmall
8,0.45,"[0, 5]","[0, 1, 3]","[0, 4]","[0, 4]","[0, 2]","[0, 2]",[0],[0],"[0, 1]",[0],[0],[0],20,"{0: [0, 5], 1: [0, 1, 3], 2: [0, 4], 3: [0, 4]...",mnist,deitsmall
9,0.50,"[0, 5]","[0, 1, 3]","[0, 4]","[0, 4]","[0, 2]","[0, 2]",[0],[0],"[0, 1]",[0],[0],[0],20,"{0: [0, 5], 1: [0, 1, 3], 2: [0, 4], 3: [0, 4]...",mnist,deitsmall
10,0.55,"[0, 5]","[0, 1, 3]","[0, 4]","[0, 4]","[0, 2]","[0, 2]",[0],[0],"[0, 1]",[0],[0],[0],20,"{0: [0, 5], 1: [0, 1, 3], 2: [0, 4], 3: [0, 4]...",mnist,deitsmall
11,0.60,"[0, 5]","[0, 1, 3]","[0, 4]","[0, 4, 5]","[0, 2, 3]","[0, 2]",[0],[0],"[0, 1]",[0],[0],[0],22,"{0: [0, 5], 1: [0, 1, 3], 2: [0, 4], 3: [0, 4,...",mnist,deitsmall
12,0.65,"[0, 5]","[0, 1, 3]","[0, 4]","[0, 1, 4, 5]","[0, 2, 3]","[0, 2]",[0],[0],"[0, 1]",[0],[0],"[0, 3]",24,"{0: [0, 5], 1: [0, 1, 3], 2: [0, 4], 3: [0, 1,...",mnist,deitsmall
13,0.70,"[0, 3, 5]","[0, 1, 3]","[0, 4]","[0, 1, 4, 5]","[0, 2, 3]","[0, 2, 4]",[0],[0],"[0, 1]","[0, 1]","[0, 1, 2]","[0, 3, 5]",30,"{0: [0, 3, 5], 1: [0, 1, 3], 2: [0, 4], 3: [0,...",mnist,deitsmall
14,0.75,"[0, 1, 3, 4, 5]","[0, 1, 3]","[0, 4]","[0, 1, 4, 5]","[0, 2, 3, 4]","[0, 1, 2, 3, 4]","[0, 2]",[0],"[0, 1, 2, 3, 4]","[0, 1, 5]","[0, 1, 2, 3]","[0, 3, 5]",41,"{0: [0, 1, 3, 4, 5], 1: [0, 1, 3], 2: [0, 4], ...",mnist,deitsmall
15,0.80,"[0, 1, 2, 3, 4, 5]","[0, 1, 2, 3]","[0, 1, 4]","[0, 1, 4, 5]","[0, 2, 3, 4]","[0, 1, 2, 3, 4, 5]","[0, 1, 2, 3, 5]","[0, 3]","[0, 1, 2, 3, 4, 5]","[0, 1, 2, 5]","[0, 1, 2, 3, 5]","[0, 3, 4, 5]",53,"{1: [0, 1, 2, 3], 2: [0, 1, 4], 3: [0, 1, 4, 5...",mnist,deitsmall
16,0.85,"[0, 1, 2, 3, 4, 5]","[0, 1, 2, 3, 4, 5]","[0, 1, 2, 3, 4, 5]","[0, 1, 3, 4, 5]","[0, 1, 2, 3, 4]","[0, 1, 2, 3, 4, 5]","[0, 1, 2, 3, 4, 5]","[0, 1, 2, 3]","[0, 1, 2, 3, 4, 5]","[0, 1, 2, 4, 5]","[0, 1, 2, 3, 4, 5]","[0, 3, 4, 5]",65,"{3: [0, 1, 3, 4, 5], 4: [0, 1, 2, 3, 4], 7: [0...",mnist,deitsmall
17,0.90,"[0, 1, 2, 3, 4, 5]","[0, 1, 2, 3, 4, 5]","[0, 1, 2, 3, 4, 5]","[0, 1, 2, 3, 4, 5]","[0, 1, 2, 3, 4, 5]","[0, 1, 2, 3, 4, 5]","[0, 1, 2, 3, 4, 5]","[0, 1, 2, 3, 4]","[0, 1, 2, 3, 4, 5]","[0, 1, 2, 3, 4, 5]","[0, 1, 2, 3, 4, 5]","[0, 1, 3, 4, 5]",70,"{7: [0, 1, 2, 3, 4], 11: [0, 1, 3, 4, 5]}",mnist,deitsmall
18,0.95,"[0, 1, 2, 3, 4, 5]","[0, 1, 2, 3, 4, 5]","[0, 1, 2, 3, 4, 5]","[0, 1, 2, 3, 4, 5]","[0, 1, 2, 3, 4, 5]","[0, 1, 2, 3, 4, 5]","[0, 1, 2, 3, 4, 5]","[0, 1, 2, 3, 4]","[0, 1, 2, 3, 4, 5]","[0, 1, 2, 3, 4, 5]","[0, 1, 2, 3, 4, 5]","[0, 1, 2, 3, 4, 5]",71,"{7: [0, 1, 2, 3, 4]}",mnist,deitsmall
19,0.05,"[0, 5]",[0],"[0, 1]",[0],[0],[0],[0],"[0, 2]",[0],[0],[0],[0],15,"{0: [0, 5], 1: [0], 2: [0, 1], 3: [0], 4: [0],...",cifar100,deitsmall
20,0.10,"[0, 5]",[0],"[0, 1, 2, 4]",[0],"[0, 3]",[0],[0],"[0, 2]",[0],[0],[0],[0],18,"{0: [0, 5], 1: [0], 2: [0, 1, 2, 4], 3: [0], 4...",cifar100,deitsmall
21,0.15,"[0, 5]",[0],"[0, 1, 2, 4]",[0],"[0, 3]",[0],[0],"[0, 2]",[0],[0],[0],[0],18,"{0: [0, 5], 1: [0], 2: [0, 1, 2, 4], 3: [0], 4...",cifar100,deitsmall
22,0.20,"[0, 3, 5]",[0],"[0, 1, 2, 4]",[0],"[0, 3]",[0],[0],"[0, 2]",[0],[0],[0],[0],19,"{0: [0, 3, 5], 1: [0], 2: [0, 1, 2, 4], 3: [0]...",cifar100,deitsmall
23,0.25,"[0, 3, 5]",[0],"[0, 1, 2, 4]",[0],"[0, 3]",[0],[0],"[0, 2]",[0],[0],[0],[0],19,"{0: [0, 3, 5], 1: [0], 2: [0, 1, 2, 4], 3: [0]...",cifar100,deitsmall
24,0.30,"[0, 3, 5]","[0, 1]","[0, 1, 2, 4]","[0, 1]","[0, 3]","[0, 1]","[0, 3, 5]","[0, 2]","[0, 2]","[0, 1]",[0],[0],26,"{0: [0, 3, 5], 1: [0, 1], 2: [0, 1, 2, 4], 3: ...",cifar100,deitsmall
25,0.35,"[0, 3, 5]","[0, 1]","[0, 1, 2, 4]","[0, 1]","[0, 2, 3]","[0, 1]","[0, 3, 4, 5]","[0, 2]","[0, 2]","[0, 1, 2]","[0, 2]",[0],30,"{0: [0, 3, 5], 1: [0, 1], 2: [0, 1, 2, 4], 3: ...",cifar100,deitsmall
26,0.40,"[0, 3, 5]","[0, 1, 4]","[0, 1, 2, 4]","[0, 1, 5]","[0, 2, 3]","[0, 1]","[0, 3, 4, 5]","[0, 2, 3]","[0, 2]","[0, 1, 2]","[0, 2]",[0],33,"{0: [0, 3, 5], 1: [0, 1, 4], 2: [0, 1, 2, 4], ...",cifar100,deitsmall
27,0.45,"[0, 3, 5]","[0, 1, 4]","[0, 1, 2, 4]","[0, 1, 2, 5]","[0, 1, 2, 3]","[0, 1, 3, 5]","[0, 3, 4, 5]","[0, 2, 3, 5]","[0, 2]","[0, 1, 2]","[0, 1, 2]",[0],39,"{0: [0, 3, 5], 1: [0, 1, 4], 2: [0, 1, 2, 4], ...",cifar100,deitsmall
28,0.50,"[0, 3, 5]","[0, 1, 3, 4]","[0, 1, 2, 3, 4]","[0, 1, 2, 3, 5]","[0, 1, 2, 3, 4]","[0, 1, 3, 4, 5]","[0, 3, 4, 5]","[0, 1, 2, 3, 5]","[0, 1, 2, 3]","[0, 1, 2]","[0, 1, 2]","[0, 1]",48,"{0: [0, 3, 5], 1: [0, 1, 3, 4], 2: [0, 1, 2, 3...",cifar100,deitsmall
29,0.55,"[0, 3, 5]","[0, 1, 2, 3, 4]","[0, 1, 2, 3, 4]","[0, 1, 2, 3, 5]","[0, 1, 2, 3, 4, 5]","[0, 1, 3, 4, 5]","[0, 1, 3, 4, 5]","[0, 1, 2, 3, 4, 5]","[0, 1, 2, 3]","[0, 1, 2, 3, 4]","[0, 1, 2]","[0, 1]",54,"{0: [0, 3, 5], 1: [0, 1, 2, 3, 4], 2: [0, 1, 2...",cifar100,deitsmall
30,0.60,"[0, 3, 5]","[0, 1, 2, 3, 4]","[0, 1, 2, 3, 4, 5]","[0, 1, 2, 3, 4, 5]","[0, 1, 2, 3, 4, 5]","[0, 1, 2, 3, 4, 5]","[0, 1, 3, 4, 5]","[0, 1, 2, 3, 4, 5]","[0, 1, 2, 3, 4, 5]","[0, 1, 2, 3, 4]","[0, 1, 2, 3]","[0, 1, 4, 5]",62,"{0: [0, 3, 5], 1: [0, 1, 2, 3, 4], 6: [0, 1, 3...",cifar100,deitsmall
31,0.65,"[0, 1, 3, 4, 5]","[0, 1, 2, 3, 4, 5]","[0, 1, 2, 3, 4, 5]","[0, 1, 2, 3, 4, 5]","[0, 1, 2, 3, 4, 5]","[0, 1, 2, 3, 4, 5]","[0, 1, 2, 3, 4, 5]","[0, 1, 2, 3, 4, 5]","[0, 1, 2, 3, 4, 5]","[0, 1, 2, 3, 4, 5]","[0, 1, 2, 3, 4, 5]","[0, 1, 3, 4, 5]",70,"{0: [0, 1, 3, 4, 5], 11: [0, 1, 3, 4, 5]}",cifar100,deitsmall
32,0.70,"[0, 1, 3, 4, 5]","[0, 1, 2, 3, 4, 5]","[0, 1, 2, 3, 4, 5]","[0, 1, 2, 3, 4, 5]","[0, 1, 2, 3, 4, 5]","[0, 1, 2, 3, 4, 5]","[0, 1, 2, 3, 4, 5]","[0, 1, 2, 3, 4, 5]","[0, 1, 2, 3, 4, 5]","[0, 1, 2, 3, 4, 5]","[0, 1, 2, 3, 4, 5]","[0, 1, 3, 4, 5]",70,"{0: [0, 1, 3, 4, 5], 11: [0, 1, 3, 4, 5]}",cifar100,deitsmall
33,0.75,"[0, 1, 2, 3, 4, 5]","[0, 1, 2, 3, 4, 5]","[0, 1, 2, 3, 4, 5]","[0, 1, 2, 3, 4, 5]","[0, 1, 2, 3, 4, 5]","[0, 1, 2, 3, 4, 5]","[0, 1, 2, 3, 4, 5]","[0, 1, 2, 3, 4, 5]","[0, 1, 2, 3, 4, 5]","[0, 1, 2, 3, 4, 5]","[0, 1, 2, 3, 4, 5]","[0, 1, 2, 3, 4, 5]",72,{},cifar100,deitsmall
34,0.80,"[0, 1, 2, 3, 4, 5]","[0, 1, 2, 3, 4, 5]","[0, 1, 2, 3, 4, 5]","[0, 1, 2, 3, 4, 5]","[0, 1, 2, 3, 4, 5]","[0, 1, 2, 3, 4, 5]","[0, 1, 2, 3, 4, 5]","[0, 1, 2, 3, 4, 5]","[0, 1, 2, 3, 4, 5]","[0, 1, 2, 3, 4, 5]","[0, 1, 2, 3, 4, 5]","[0, 1, 2, 3, 4, 5]",72,{},cifar100,deitsmall
35,0.85,"[0, 1, 2, 3, 4, 5]","[0, 1, 2, 3, 4, 5]","[0, 1, 2, 3, 4, 5]","[0, 1, 2, 3, 4, 5]","[0, 1, 2, 3, 4, 5]","[0, 1, 2, 3, 4, 5]","[0, 1, 2, 3, 4, 5]","[0, 1, 2, 3, 4, 5]","[0, 1, 2, 3, 4, 5]","[0, 1, 2, 3, 4, 5]","[0, 1, 2, 3, 4, 5]","[0, 1, 2, 3, 4, 5]",72,{},cifar100,deitsmall
36,0.90,"[0, 1, 2, 3, 4, 5]","[0, 1, 2, 3, 4, 5]","[0, 1, 2, 3, 4, 5]","[0, 1, 2, 3, 4, 5]","[0, 1, 2, 3, 4, 5]","[0, 1, 2, 3, 4, 5]","[0, 1, 2, 3, 4, 5]","[0, 1, 2, 3, 4, 5]","[0, 1, 2, 3, 4, 5]","[0, 1, 2, 3, 4, 5]","[0, 1, 2, 3, 4, 5]","[0, 1, 2, 3, 4, 5]",72,{},cifar100,deitsmall
37,0.95,"[0, 1, 2, 3, 4, 5]","[0, 1, 2, 3, 4, 5]","[0, 1, 2, 3, 4, 5]","[0, 1, 2, 3, 4, 5]","[0, 1, 2, 3, 4, 5]","[0, 1, 2, 3, 4, 5]","[0, 1, 2, 3, 4, 5]","[0, 1, 2, 3, 4, 5]","[0, 1, 2, 3, 4, 5]","[0, 1, 2, 3, 4, 5]","[0, 1, 2, 3, 4, 5]","[0, 1, 2, 3, 4, 5]",72,{},cifar100,deitsmall
38,0.05,"[0, 1, 2, 3, 4]","[0, 2, 3, 4]",[0],"[0, 2]","[0, 1]",[0],"[0, 1]","[0, 3]",[0],[0],[0],[0],23,"{0: [0, 1, 2, 3, 4], 1: [0, 2, 3, 4], 2: [0], ...",imagenet1k,deitsmall
39,0.10,"[0, 1, 2, 3, 4]","[0, 1, 2, 3, 4]",[0],"[0, 2, 4]","[0, 1]",[0],"[0, 1]","[0, 1, 3]",[0],[0],[0],[0],26,"{0: [0, 1, 2, 3, 4], 1: [0, 1, 2, 3, 4], 2: [0...",imagenet1k,deitsmall
40,0.15,"[0, 1, 2, 3, 4]","[0, 1, 2, 3, 4, 5]","[0, 1]","[0, 2, 4]","[0, 1]",[0],"[0, 1]","[0, 1, 3]",[0],[0],[0],[0],28,"{0: [0, 1, 2, 3, 4], 2: [0, 1], 3: [0, 2, 4], ...",imagenet1k,deitsmall
41,0.20,"[0, 1, 2, 3, 4, 5]","[0, 1, 2, 3, 4, 5]","[0, 1]","[0, 2, 4, 5]","[0, 1]",[0],"[0, 1]","[0, 1, 3]",[0],[0],"[0, 1]",[0],31,"{2: [0, 1], 3: [0, 2, 4, 5], 4: [0, 1], 5: [0]...",imagenet1k,deitsmall
42,0.25,"[0, 1, 2, 3, 4, 5]","[0, 1, 2, 3, 4, 5]","[0, 1, 2]","[0, 2, 4, 5]","[0, 1]",[0],"[0, 1]","[0, 1, 3]",[0],[0],"[0, 1]","[0, 4]",33,"{2: [0, 1, 2], 3: [0, 2, 4, 5], 4: [0, 1], 5: ...",imagenet1k,deitsmall
43,0.30,"[0, 1, 2, 3, 4, 5]","[0, 1, 2, 3, 4, 5]","[0, 1, 2, 4]","[0, 2, 4, 5]","[0, 1]","[0, 1]","[0, 1, 2]","[0, 1, 3, 4, 5]",[0],[0],"[0, 1, 2]","[0, 4]",39,"{2: [0, 1, 2, 4], 3: [0, 2, 4, 5], 4: [0, 1], ...",imagenet1k,deitsmall
44,0.35,"[0, 1, 2, 3, 4, 5]","[0, 1, 2, 3, 4, 5]","[0, 1, 2, 4, 5]","[0, 1, 2, 4, 5]","[0, 1]","[0, 1]","[0, 1, 2]","[0, 1, 3, 4, 5]","[0, 3, 4]","[0, 2, 4]","[0, 1, 2]","[0, 4]",45,"{2: [0, 1, 2, 4, 5], 3: [0, 1, 2, 4, 5], 4: [0...",imagenet1k,deitsmall
45,0.40,"[0, 1, 2, 3, 4, 5]","[0, 1, 2, 3, 4, 5]","[0, 1, 2, 4, 5]","[0, 1, 2, 3, 4, 5]","[0, 1, 2, 4]","[0, 1, 2]","[0, 1, 2, 5]","[0, 1, 3, 4, 5]","[0, 3, 4]","[0, 2, 4]","[0, 1, 2, 3]","[0, 2, 3, 4]",53,"{2: [0, 1, 2, 4, 5], 4: [0, 1, 2, 4], 5: [0, 1...",imagenet1k,deitsmall
46,0.45,"[0, 1, 2, 3, 4, 5]","[0, 1, 2, 3, 4, 5]","[0, 1, 2, 3, 4, 5]","[0, 1, 2, 3, 4, 5]","[0, 1, 2, 3, 4, 5]","[0, 1, 2, 3, 4]","[0, 1, 2, 4, 5]","[0, 1, 3, 4, 5]","[0, 3, 4]","[0, 2, 4]","[0, 1, 2, 3, 4]","[0, 1, 2, 3, 4]",61,"{5: [0, 1, 2, 3, 4], 6: [0, 1, 2, 4, 5], 7: [0...",imagenet1k,deitsmall
47,0.50,"[0, 1, 2, 3, 4, 5]","[0, 1, 2, 3, 4, 5]","[0, 1, 2, 3, 4, 5]","[0, 1, 2, 3, 4, 5]","[0, 1, 2, 3, 4, 5]","[0, 1, 2, 3, 4, 5]","[0, 1, 2, 3, 4, 5]","[0, 1, 2, 3, 4, 5]","[0, 1, 3, 4, 5]","[0, 1, 2, 3, 4, 5]","[0, 1, 2, 3, 4]","[0, 1, 2, 3, 4, 5]",70,"{8: [0, 1, 3, 4, 5], 10: [0, 1, 2, 3, 4]}",imagenet1k,deitsmall
48,0.55,"[0, 1, 2, 3, 4, 5]","[0, 1, 2, 3, 4, 5]","[0, 1, 2, 3, 4, 5]","[0, 1, 2, 3, 4, 5]","[0, 1, 2, 3, 4, 5]","[0, 1, 2, 3, 4, 5]","[0, 1, 2, 3, 4, 5]","[0, 1, 2, 3, 4, 5]","[0, 1, 3, 4, 5]","[0, 1, 2, 3, 4, 5]","[0, 1, 2, 3, 4, 5]","[0, 1, 2, 3, 4, 5]",71,"{8: [0, 1, 3, 4, 5]}",imagenet1k,deitsmall
49,0.60,"[0, 1, 2, 3, 4, 5]","[0, 1, 2, 3, 4, 5]","[0, 1, 2, 3, 4, 5]","[0, 1, 2, 3, 4, 5]","[0, 1, 2, 3, 4, 5]","[0, 1, 2, 3, 4, 5]","[0, 1, 2, 3, 4, 5]","[0, 1, 2, 3, 4, 5]","[0, 1, 2, 3, 4, 5]","[0, 1, 2, 3, 4, 5]","[0, 1, 2, 3, 4, 5]","[0, 1, 2, 3, 4, 5]",72,{},imagenet1k,deitsmall
50,0.65,"[0, 1, 2, 3, 4, 5]","[0, 1, 2, 3, 4, 5]","[0, 1, 2, 3, 4, 5]","[0, 1, 2, 3, 4, 5]","[0, 1, 2, 3, 4, 5]","[0, 1, 2, 3, 4, 5]","[0, 1, 2, 3, 4, 5]","[0, 1, 2, 3, 4, 5]","[0, 1, 2, 3, 4, 5]","[0, 1, 2, 3, 4, 5]","[0, 1, 2, 3, 4, 5]","[0, 1, 2, 3, 4, 5]",72,{},imagenet1k,deitsmall
51,0.70,"[0, 1, 2, 3, 4, 5]","[0, 1, 2, 3, 4, 5]","[0, 1, 2, 3, 4, 5]","[0, 1, 2, 3, 4, 5]","[0, 1, 2, 3, 4, 5]","[0, 1, 2, 3, 4, 5]","[0, 1, 2, 3, 4, 5]","[0, 1, 2, 3, 4, 5]","[0, 1, 2, 3, 4, 5]","[0, 1, 2, 3, 4, 5]","[0, 1, 2, 3, 4, 5]","[0, 1, 2, 3, 4, 5]",72,{},imagenet1k,deitsmall
52,0.75,"[0, 1, 2, 3, 4, 5]","[0, 1, 2, 3, 4, 5]","[0, 1, 2, 3, 4, 5]","[0, 1, 2, 3, 4, 5]","[0, 1, 2, 3, 4, 5]","[0, 1, 2, 3, 4, 5]","[0, 1, 2, 3, 4, 5]","[0, 1, 2, 3, 4, 5]","[0, 1, 2, 3, 4, 5]","[0, 1, 2, 3, 4, 5]","[0, 1, 2, 3, 4, 5]","[0, 1, 2, 3, 4, 5]",72,{},imagenet1k,deitsmall
53,0.80,"[0, 1, 2, 3, 4, 5]","[0, 1, 2, 3, 4, 5]","[0, 1, 2, 3, 4, 5]","[0, 1, 2, 3, 4, 5]","[0, 1, 2, 3, 4, 5]","[0, 1, 2, 3, 4, 5]","[0, 1, 2, 3, 4, 5]","[0, 1, 2, 3, 4, 5]","[0, 1, 2, 3, 4, 5]","[0, 1, 2, 3, 4, 5]","[0, 1, 2, 3, 4, 5]","[0, 1, 2, 3, 4, 5]",72,{},imagenet1k,deitsmall
54,0.85,"[0, 1, 2, 3, 4, 5]","[0, 1, 2, 3, 4, 5]","[0, 1, 2, 3, 4, 5]","[0, 1, 2, 3, 4, 5]","[0, 1, 2, 3, 4, 5]","[0, 1, 2, 3, 4, 5]","[0, 1, 2, 3, 4, 5]","[0, 1, 2, 3, 4, 5]","[0, 1, 2, 3, 4, 5]","[0, 1, 2, 3, 4, 5]","[0, 1, 2, 3, 4, 5]","[0, 1, 2, 3, 4, 5]",72,{},imagenet1k,deitsmall
55,0.90,"[0, 1, 2, 3, 4, 5]","[0, 1, 2, 3, 4, 5]","[0, 1, 2, 3, 4, 5]","[0, 1, 2, 3, 4, 5]","[0, 1, 2, 3, 4, 5]","[0, 1, 2, 3, 4, 5]","[0, 1, 2, 3, 4, 5]","[0, 1, 2, 3, 4, 5]","[0, 1, 2, 3, 4, 5]","[0, 1, 2, 3, 4, 5]","[0, 1, 2, 3, 4, 5]","[0, 1, 2, 3, 4, 5]",72,{},imagenet1k,deitsmall
56,0.95,"[0, 1, 2, 3, 4, 5]","[0, 1, 2, 3, 4, 5]","[0, 1, 2, 3, 4, 5]","[0, 1, 2, 3, 4, 5]","[0, 1, 2, 3, 4, 5]","[0, 1, 2, 3, 4, 5]","[0, 1, 2, 3, 4, 5]","[0, 1, 2, 3, 4, 5]","[0, 1, 2, 3, 4, 5]","[0, 1, 2, 3, 4, 5]","[0, 1, 2, 3, 4, 5]","[0, 1, 2, 3, 4, 5]",72,{},imagenet1k,deitsmall

In [12]:
tab["head_dict"] = tab.apply(lambda row: {int(f"{i}"): row[f"layer_{i}_keep"] for i in range(0, 12) if len(row[f"layer_{i}_keep"]) < 6}, axis=1)

In [13]:
tab

,threshold,layer_0_keep,layer_1_keep,layer_2_keep,layer_3_keep,layer_4_keep,layer_5_keep,layer_6_keep,layer_7_keep,layer_8_keep,layer_9_keep,layer_10_keep,layer_11_keep,total_heads_kept,head_dict
0,0.05,[0],[0],[0],"[0, 4]",[0],[0],[0],[0],"[0, 1]",[0],[0],[0],14,"{0: [0], 1: [0], 2: [0], 3: [0, 4], 4: [0], 5:..."
1,0.10,[0],[0],[0],"[0, 4]",[0],[0],[0],[0],"[0, 1]",[0],[0],[0],14,"{0: [0], 1: [0], 2: [0], 3: [0, 4], 4: [0], 5:..."
2,0.15,[0],[0],[0],"[0, 4]",[0],[0],[0],[0],"[0, 1]",[0],[0],[0],14,"{0: [0], 1: [0], 2: [0], 3: [0, 4], 4: [0], 5:..."
3,0.20,[0],[0],[0],"[0, 4]",[0],[0],[0],[0],"[0, 1]",[0],[0],[0],14,"{0: [0], 1: [0], 2: [0], 3: [0, 4], 4: [0], 5:..."
4,0.25,[0],"[0, 3]",[0],"[0, 4]",[0],[0],[0],[0],"[0, 1]",[0],[0],[0],15,"{0: [0], 1: [0, 3], 2: [0], 3: [0, 4], 4: [0],..."
5,0.30,[0],"[0, 3]",[0],"[0, 4]",[0],[0],[0],[0],"[0, 1]",[0],[0],[0],15,"{0: [0], 1: [0, 3], 2: [0], 3: [0, 4], 4: [0],..."
6,0.35,[0],"[0, 3]",[0],"[0, 4]","[0, 2]","[0, 2]",[0],[0],"[0, 1]",[0],[0],[0],17,"{0: [0], 1: [0, 3], 2: [0], 3: [0, 4], 4: [0, ..."
7,0.40,[0],"[0, 3]","[0, 4]","[0, 4]","[0, 2]","[0, 2]",[0],[0],"[0, 1]",[0],[0],[0],18,"{0: [0], 1: [0, 3], 2: [0, 4], 3: [0, 4], 4: [..."
8,0.45,"[0, 5]","[0, 1, 3]","[0, 4]","[0, 4]","[0, 2]","[0, 2]",[0],[0],"[0, 1]",[0],[0],[0],20,"{0: [0, 5], 1: [0, 1, 3], 2: [0, 4], 3: [0, 4]..."
9,0.50,"[0, 5]","[0, 1, 3]","[0, 4]","[0, 4]","[0, 2]","[0, 2]",[0],[0],"[0, 1]",[0],[0],[0],20,"{0: [0, 5], 1: [0, 1, 3], 2: [0, 4], 3: [0, 4]..."
10,0.55,"[0, 5]","[0, 1, 3]","[0, 4]","[0, 4]","[0, 2]","[0, 2]",[0],[0],"[0, 1]",[0],[0],[0],20,"{0: [0, 5], 1: [0, 1, 3], 2: [0, 4], 3: [0, 4]..."
11,0.60,"[0, 5]","[0, 1, 3]","[0, 4]","[0, 4, 5]","[0, 2, 3]","[0, 2]",[0],[0],"[0, 1]",[0],[0],[0],22,"{0: [0, 5], 1: [0, 1, 3], 2: [0, 4], 3: [0, 4,..."
12,0.65,"[0, 5]","[0, 1, 3]","[0, 4]","[0, 1, 4, 5]","[0, 2, 3]","[0, 2]",[0],[0],"[0, 1]",[0],[0],"[0, 3]",24,"{0: [0, 5], 1: [0, 1, 3], 2: [0, 4], 3: [0, 1,..."
13,0.70,"[0, 3, 5]","[0, 1, 3]","[0, 4]","[0, 1, 4, 5]","[0, 2, 3]","[0, 2, 4]",[0],[0],"[0, 1]","[0, 1]","[0, 1, 2]","[0, 3, 5]",30,"{0: [0, 3, 5], 1: [0, 1, 3], 2: [0, 4], 3: [0,..."
14,0.75,"[0, 1, 3, 4, 5]","[0, 1, 3]","[0, 4]","[0, 1, 4, 5]","[0, 2, 3, 4]","[0, 1, 2, 3, 4]","[0, 2]",[0],"[0, 1, 2, 3, 4]","[0, 1, 5]","[0, 1, 2, 3]","[0, 3, 5]",41,"{0: [0, 1, 3, 4, 5], 1: [0, 1, 3], 2: [0, 4], ..."
15,0.80,"[0, 1, 2, 3, 4, 5]","[0, 1, 2, 3]","[0, 1, 4]","[0, 1, 4, 5]","[0, 2, 3, 4]","[0, 1, 2, 3, 4, 5]","[0, 1, 2, 3, 5]","[0, 3]","[0, 1, 2, 3, 4, 5]","[0, 1, 2, 5]","[0, 1, 2, 3, 5]","[0, 3, 4, 5]",53,"{1: [0, 1, 2, 3], 2: [0, 1, 4], 3: [0, 1, 4, 5..."
16,0.85,"[0, 1, 2, 3, 4, 5]","[0, 1, 2, 3, 4, 5]","[0, 1, 2, 3, 4, 5]","[0, 1, 3, 4, 5]","[0, 1, 2, 3, 4]","[0, 1, 2, 3, 4, 5]","[0, 1, 2, 3, 4, 5]","[0, 1, 2, 3]","[0, 1, 2, 3, 4, 5]","[0, 1, 2, 4, 5]","[0, 1, 2, 3, 4, 5]","[0, 3, 4, 5]",65,"{3: [0, 1, 3, 4, 5], 4: [0, 1, 2, 3, 4], 7: [0..."
17,0.90,"[0, 1, 2, 3, 4, 5]","[0, 1, 2, 3, 4, 5]","[0, 1, 2, 3, 4, 5]","[0, 1, 2, 3, 4, 5]","[0, 1, 2, 3, 4, 5]","[0, 1, 2, 3, 4, 5]","[0, 1, 2, 3, 4, 5]","[0, 1, 2, 3, 4]","[0, 1, 2, 3, 4, 5]","[0, 1, 2, 3, 4, 5]","[0, 1, 2, 3, 4, 5]","[0, 1, 3, 4, 5]",70,"{7: [0, 1, 2, 3, 4], 11: [0, 1, 3, 4, 5]}"
18,0.95,"[0, 1, 2, 3, 4, 5]","[0, 1, 2, 3, 4, 5]","[0, 1, 2, 3, 4, 5]","[0, 1, 2, 3, 4, 5]","[0, 1, 2, 3, 4, 5]","[0, 1, 2, 3, 4, 5]","[0, 1, 2, 3, 4, 5]","[0, 1, 2, 3, 4]","[0, 1, 2, 3, 4, 5]","[0, 1, 2, 3, 4, 5]","[0, 1, 2, 3, 4, 5]","[0, 1, 2, 3, 4, 5]",71,"{7: [0, 1, 2, 3, 4]}"